name: Publish Pages

on:
  push:
    branches: [main]

jobs:
  build:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: 'https://npm.pkg.github.com'

      - name: Setup Pages
        uses: actions/configure-pages@v6
        id: setup

      - name: Build Pages
        run: |
          npm clean-install --ignore-scripts
          npm run build-demo
        env:
          VITE_BASE_URL: "${{steps.setup.outputs.base_url}}"

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: demo

      - name: Deploy Pages
        uses: actions/deploy-pages@v5
